// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "system-re",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://system-re.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:f5ad41d7-cb2e-4379-a0f5-92f2ff611c4d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vJnA1dqJi",
    "aws_user_pools_web_client_id": "3v5ccfnba1fl9bv8u2f7nvvvcf"
};


export default awsmobile;
